import { Screening, DashboardStats } from './types';

export const dashboardStats: DashboardStats = {
  todayCount: 12,
  weekCount: 47,
  avgScore: 72,
  passRate: 64,
};

const salesCriteria = [
  { id: 'sc1', criterionName: 'Years of experience in real estate or property sales', isMustHave: true, status: 'Met' as const, reasoning: '6 years of residential and commercial property sales in Delhi-NCR region, exceeding the 3-year minimum requirement.', weight: 10 },
  { id: 'sc2', criterionName: 'Knowledge of Delhi-NCR real estate market', isMustHave: false, status: 'Met' as const, reasoning: 'Extensive experience across Gurgaon, Noida, and Greater Noida markets. Mentions specific micro-markets and pricing trends.', weight: 8 },
  { id: 'sc3', criterionName: 'CRM tool experience', isMustHave: false, status: 'Met' as const, reasoning: 'Proficient in Salesforce CRM with 4 years of documented usage. Also mentions HubSpot experience.', weight: 6 },
  { id: 'sc4', criterionName: 'Communication skills evidence', isMustHave: false, status: 'Met' as const, reasoning: 'Led client presentations, conducted property walkthroughs, and managed stakeholder communications regularly.', weight: 5 },
  { id: 'sc5', criterionName: 'Negotiation ability or evidence', isMustHave: false, status: 'Partially Met' as const, reasoning: 'Mentions closing deals but no specific negotiation achievements or training documented.', weight: 7 },
  { id: 'sc6', criterionName: 'Target/quota achievement track record', isMustHave: false, status: 'Met' as const, reasoning: 'Consistently exceeded quarterly targets by 15-20% over last 3 years. Specific numbers provided.', weight: 8 },
  { id: 'sc7', criterionName: 'Relevant certifications (RERA, etc.)', isMustHave: false, status: 'Not Met' as const, reasoning: 'No RERA registration or real estate certifications mentioned in the resume.', weight: 4 },
  { id: 'sc8', criterionName: 'Educational background', isMustHave: false, status: 'Met' as const, reasoning: 'MBA in Marketing from a recognized university. Strong academic foundation.', weight: 5 },
  { id: 'sc9', criterionName: 'Team leadership experience', isMustHave: false, status: 'Partially Met' as const, reasoning: 'Managed a team of 3 junior sales associates. Limited large-team leadership.', weight: 6 },
  { id: 'sc10', criterionName: 'Client relationship management evidence', isMustHave: false, status: 'Met' as const, reasoning: 'Maintained portfolio of 50+ high-value clients. References to repeat business and referrals.', weight: 7 },
  { id: 'sc11', criterionName: 'Market analysis or research skills', isMustHave: false, status: 'Partially Met' as const, reasoning: 'Some market research mentioned but no structured analysis or reports referenced.', weight: 4 },
  { id: 'sc12', criterionName: 'Presentation or pitching experience', isMustHave: false, status: 'Met' as const, reasoning: 'Regular client presentations and property showcase events. Comfortable with large audiences.', weight: 5 },
  { id: 'sc13', criterionName: 'Multilingual ability (Hindi + English minimum)', isMustHave: false, status: 'Met' as const, reasoning: 'Fluent in Hindi, English, and Punjabi. Multilingual advantage confirmed.', weight: 5 },
  { id: 'sc14', criterionName: 'Stability (tenure at previous companies)', isMustHave: false, status: 'Met' as const, reasoning: 'Two employers over 6 years. Average tenure of 3 years — good stability.', weight: 5 },
  { id: 'sc15', criterionName: 'References or recommendations mentioned', isMustHave: false, status: 'Not Met' as const, reasoning: 'No references or recommendations section in the resume.', weight: 3 },
];

export const mockScreenings: Screening[] = [
  {
    id: '1',
    userId: 'u1',
    userName: 'Priya Sharma',
    role: 'Sales',
    candidateName: 'Rahul Mehta',
    candidateEmail: 'rahul.mehta@email.com',
    candidatePhone: '+91 98765 43210',
    candidateLocation: 'Gurgaon, Haryana',
    currentRole: 'Senior Sales Executive',
    currentCompany: 'Godrej Properties',
    overallScore: 82,
    recommendation: 'Interview',
    highlights: [
      '6 years of Delhi-NCR real estate sales experience',
      'Consistently exceeded quarterly targets by 15-20%',
      'Strong CRM proficiency with Salesforce and HubSpot',
      'Portfolio of 50+ high-value client relationships',
      'MBA in Marketing with strong academic record',
    ],
    redFlags: [
      'No RERA registration or certifications',
      'Limited large-team leadership experience',
      'No references section in resume',
    ],
    criteriaResults: salesCriteria,
    createdAt: '2026-08-27T10:30:00Z',
  },
  {
    id: '2',
    userId: 'u1',
    userName: 'Priya Sharma',
    role: 'Sales',
    candidateName: 'Anita Kapoor',
    candidateEmail: 'anita.k@email.com',
    candidatePhone: '+91 99887 66554',
    candidateLocation: 'Noida, UP',
    currentRole: 'Area Sales Manager',
    currentCompany: 'DLF Limited',
    overallScore: 91,
    recommendation: 'Interview',
    highlights: [
      '9 years in premium real estate sales across Delhi-NCR',
      'Led team of 12 sales professionals',
      'RERA certified with multiple industry recognitions',
      'Closed deals worth INR 200+ crores cumulatively',
    ],
    redFlags: [
      'Short stint at one employer (11 months)',
    ],
    criteriaResults: salesCriteria.map((c, i) => ({
      ...c,
      id: `sc2-${i}`,
      status: i === 6 ? 'Met' as const : c.status,
      reasoning: i === 6 ? 'RERA certified. Also holds CREDAI membership.' : c.reasoning,
    })),
    createdAt: '2026-08-27T09:15:00Z',
  },
  {
    id: '3',
    userId: 'u2',
    userName: 'Amit Verma',
    role: 'HR',
    candidateName: 'Sneha Reddy',
    candidateEmail: 'sneha.r@email.com',
    candidatePhone: '+91 88776 55443',
    candidateLocation: 'Delhi',
    currentRole: 'HR Manager',
    currentCompany: 'Tata Realty',
    overallScore: 76,
    recommendation: 'Interview',
    highlights: [
      '7 years in HR with 4 years in real estate sector',
      'Strong recruitment and onboarding experience',
      'Proficient in SAP SuccessFactors HRMS',
      'Experience with Indian labour law compliance',
    ],
    redFlags: [
      'Limited data-driven HR / analytics experience',
      'No employer branding initiatives mentioned',
    ],
    criteriaResults: salesCriteria.map((c, i) => ({
      ...c,
      id: `hr-${i}`,
      criterionName: ['HR qualification or certification', 'Recruitment experience', 'Employee management', 'Indian labour laws', 'HRMS tool experience', 'Organizational skills', 'Conflict resolution', 'Training programs', 'Performance management', 'Onboarding experience', 'Employer branding', 'HR analytics', 'Communication skills', 'Educational background', 'Stability and tenure'][i] || c.criterionName,
      isMustHave: i < 2,
    })),
    createdAt: '2026-08-26T14:45:00Z',
  },
  {
    id: '4',
    userId: 'u1',
    userName: 'Priya Sharma',
    role: 'Technology',
    candidateName: 'Vikram Singh',
    candidateEmail: 'vikram.s@email.com',
    candidatePhone: '+91 77665 44332',
    candidateLocation: 'Bangalore',
    currentRole: 'Full Stack Developer',
    currentCompany: 'Infosys',
    overallScore: 68,
    recommendation: 'Interview',
    highlights: [
      'B.Tech in Computer Science from NIT',
      '5 years of full stack development experience',
      'AWS certified Solutions Architect',
      'Strong API development and microservices experience',
    ],
    redFlags: [
      'No real estate or ERP domain experience',
      'Currently based in Bangalore — relocation needed',
      'No documentation or technical writing samples',
    ],
    criteriaResults: salesCriteria.map((c, i) => ({
      ...c,
      id: `tech-${i}`,
      criterionName: ['Technical degree', 'Programming proficiency', 'ERP experience', 'Project delivery', 'Technical certifications', 'Problem-solving', 'Database management', 'API development', 'Version control / CI/CD', 'Collaboration tools', 'Security awareness', 'Documentation', 'Agile/Scrum', 'Educational background', 'Stability'][i] || c.criterionName,
      isMustHave: i === 0,
      status: i === 2 ? 'Not Met' as const : i === 11 ? 'Not Met' as const : c.status,
    })),
    createdAt: '2026-08-26T11:20:00Z',
  },
  {
    id: '5',
    userId: 'u2',
    userName: 'Amit Verma',
    role: 'Sales',
    candidateName: 'Deepak Tiwari',
    candidateEmail: 'deepak.t@email.com',
    candidatePhone: '+91 66554 33221',
    candidateLocation: 'Mumbai',
    currentRole: 'Sales Associate',
    currentCompany: 'Prestige Group',
    overallScore: 45,
    recommendation: 'Do Not Interview',
    highlights: [
      '2 years of real estate sales experience',
      'Good communication skills noted',
    ],
    redFlags: [
      'Below minimum 3-year experience requirement (must-have not met)',
      'No Delhi-NCR market knowledge',
      'No CRM tool experience mentioned',
      'Frequent job changes — 3 employers in 2 years',
    ],
    criteriaResults: salesCriteria.map((c, i) => ({
      ...c,
      id: `s5-${i}`,
      status: i === 0 ? 'Not Met' as const : i < 4 ? 'Partially Met' as const : 'Not Met' as const,
    })),
    createdAt: '2026-08-25T16:00:00Z',
  },
  {
    id: '6',
    userId: 'u1',
    userName: 'Priya Sharma',
    role: 'HR',
    candidateName: 'Meera Patel',
    candidateEmail: 'meera.p@email.com',
    candidatePhone: '+91 55443 22110',
    candidateLocation: 'Gurgaon',
    currentRole: 'Senior HR Executive',
    currentCompany: 'Sobha Limited',
    overallScore: 85,
    recommendation: 'Interview',
    highlights: [
      '8 years HR experience with real estate focus',
      'Led campus recruitment drives at 15+ colleges',
      'Implemented performance management system from scratch',
      'SHRM-CP certified',
    ],
    redFlags: [
      'Limited conflict resolution examples',
    ],
    criteriaResults: salesCriteria.map((c, i) => ({
      ...c,
      id: `hr2-${i}`,
      criterionName: ['HR qualification', 'Recruitment experience', 'Employee management', 'Labour laws', 'HRMS tools', 'Organizational skills', 'Conflict resolution', 'Training programs', 'Performance management', 'Onboarding', 'Employer branding', 'HR analytics', 'Communication', 'Education', 'Stability'][i] || c.criterionName,
      isMustHave: i < 2,
      status: i === 6 ? 'Partially Met' as const : 'Met' as const,
    })),
    createdAt: '2026-08-25T09:30:00Z',
  },
  {
    id: '7',
    userId: 'u2',
    userName: 'Amit Verma',
    role: 'Technology',
    candidateName: 'Arjun Nair',
    candidateEmail: 'arjun.n@email.com',
    candidatePhone: '+91 44332 11009',
    candidateLocation: 'Hyderabad',
    currentRole: 'DevOps Engineer',
    currentCompany: 'Wipro',
    overallScore: 58,
    recommendation: 'Do Not Interview',
    highlights: [
      'AWS and Azure certified',
      'Strong CI/CD pipeline experience',
    ],
    redFlags: [
      'No frontend development skills',
      'No real estate domain experience',
      'Limited API development experience',
      'No Agile/Scrum methodology evidence',
    ],
    criteriaResults: salesCriteria.map((c, i) => ({
      ...c,
      id: `tech2-${i}`,
      criterionName: ['Technical degree', 'Programming proficiency', 'ERP experience', 'Project delivery', 'Certifications', 'Problem-solving', 'Database management', 'API development', 'Version control', 'Collaboration tools', 'Security', 'Documentation', 'Agile/Scrum', 'Education', 'Stability'][i] || c.criterionName,
      isMustHave: i === 0,
      status: i < 2 ? 'Met' as const : i === 4 ? 'Met' as const : i === 8 ? 'Met' as const : 'Not Met' as const,
    })),
    createdAt: '2026-08-24T13:45:00Z',
  },
  {
    id: '8',
    userId: 'u1',
    userName: 'Priya Sharma',
    role: 'Sales',
    candidateName: 'Kavita Deshmukh',
    candidateEmail: 'kavita.d@email.com',
    candidatePhone: '+91 33221 00998',
    candidateLocation: 'Delhi',
    currentRole: 'Business Development Manager',
    currentCompany: 'Prestige Estates',
    overallScore: 88,
    recommendation: 'Interview',
    highlights: [
      '10 years of premium property sales in Delhi-NCR',
      'Built and managed team of 8 sales executives',
      'Track record of INR 150+ crore in annual sales',
      'RERA registered agent',
      'Excellent client retention rate of 85%',
    ],
    redFlags: [],
    criteriaResults: salesCriteria.map((c) => ({
      ...c,
      id: `s8-${c.id}`,
      status: 'Met' as const,
    })),
    createdAt: '2026-08-24T10:15:00Z',
  },
];

export const mockUsers = [
  { id: 'u1', name: 'Priya Sharma', email: 'priya.sharma@tdiinfratech.com', role: 'admin' as const, status: 'active' as const, lastActiveAt: '2026-08-27T10:30:00Z' },
  { id: 'u2', name: 'Amit Verma', email: 'amit.verma@tdiinfratech.com', role: 'user' as const, status: 'active' as const, lastActiveAt: '2026-08-27T09:45:00Z' },
  { id: 'u3', name: 'Neha Gupta', email: 'neha.gupta@tdiinfratech.com', role: 'user' as const, status: 'active' as const, lastActiveAt: '2026-08-26T17:00:00Z' },
  { id: 'u4', name: 'Rajesh Kumar', email: 'rajesh.k@tdiinfratech.com', role: 'user' as const, status: 'deactivated' as const, lastActiveAt: '2026-07-15T12:00:00Z' },
  { id: 'u5', name: 'Sonia Malik', email: 'sonia.m@tdiinfratech.com', role: 'user' as const, status: 'active' as const, lastActiveAt: '2026-08-27T08:30:00Z' },
];
